#!/usr/bin/env python3
"""Generate apps/client/src/gui/tids.ts from the decompiled TextIDs.as (TID_* name -> line index in Locale/XX.txt)."""
import re, sys, pathlib
root = pathlib.Path(__file__).resolve().parent.parent
src = (root / "decompiled/scripts/TextIDs.as").read_text(encoding="utf-8")
pairs = re.findall(r"const (TID_\w+):int = (\d+);", src)
out = ["// GENERATED by tools/gen_tids.py from decompiled TextIDs.as. TID name -> line index in Datas/Locale/<LANG>.txt.",
       "export const TID: Readonly<Record<string, number>> = {"]
out += [f"  {n}: {v}," for n, v in pairs]
out.append("};")
(root / "apps/client/src/gui/tids.ts").write_text("\n".join(out) + "\n", encoding="utf-8")
print(len(pairs), "ids")
