#!/usr/bin/env python3
"""Group the 318 mission definitions into MECHANISM CLASSES and pick representatives.

Mission behaviour is determined by: event type, how the parameter matches (none / item group / specific sku /
sub-group / type%duration), whether the target amount is 1 or >1, whether a threshold `condition` exists, whether
the mission has prerequisites (level / unlockSku), and the shape of the reward in each reward group.
Everything else (names, amounts, rewards) is data. Writes tools/missions/out/classes.json and docs/missions-classes.md.
Usage: python3 tools/missions/classes.py
"""
import collections, json
from common import ROOT, OUT, load_missions, load_item_skus, load_item_keys, param_kind, reward_form

DEFERRED_TYPES = {"upgrade", "collectUpgraded", "visitPartner", "visitCity", "investment", "investmentDone", "askForHelp", "beat"}


def class_key(m, skus, keys):
    amount = int(m.get("amount", "0") or 0)
    return "|".join([
        m["type"],
        "p:" + param_kind(m, skus, keys),
        "n:" + ("1" if amount <= 1 else ">1"),
        "c:" + ("thr" if m.get("condition") else "-"),
        "u:" + ("sku" if m.get("unlockSku") else "lvl" if m.get("unlockLevel") else "none"),
    ])


def reward_key(m):
    """Reward handling is separate code from event matching: classify it on its own (3 reward groups)."""
    return "|".join(["r0:" + reward_form(m.get("rewardType")), "r1:" + reward_form(m.get("rewardTypeABtest1")), "r2:" + reward_form(m.get("rewardTypeABtest2"))])


def main():
    OUT.mkdir(parents=True, exist_ok=True)
    skus, keys = load_item_skus(), load_item_keys()
    ms = load_missions()
    classes = collections.OrderedDict()
    for m in ms:
        classes.setdefault(class_key(m, skus, keys), []).append(m)
    result = []
    for i, (k, members) in enumerate(sorted(classes.items(), key=lambda kv: (kv[0].split("|")[0], kv[0]))):
        defaults = [m for m in members if m["_set"] == "default"]
        rep = (defaults or members)[0]
        # second representative from the other set when it exists (checks both reward/data variants)
        other = [m for m in members if m["_set"] != rep["_set"]]
        result.append({
            "class": f"C{i + 1:02d}",
            "key": k,
            "type": k.split("|")[0],
            "deferred": k.split("|")[0] in DEFERRED_TYPES,
            "members": [m["sku"] for m in members],
            "default_members": [m["sku"] for m in defaults],
            "representative": rep["sku"],
            "second_representative": other[0]["sku"] if other else None,
        })
    rewards = collections.OrderedDict()
    for m in ms:
        rewards.setdefault(reward_key(m), []).append(m)
    reward_result = []
    for i, (k, members) in enumerate(sorted(rewards.items())):
        defaults = [m for m in members if m["_set"] == "default"]
        reward_result.append({"class": f"R{i + 1:02d}", "key": k, "members": [m["sku"] for m in members],
                              "representative": (defaults or members)[0]["sku"]})
    (OUT / "classes.json").write_text(json.dumps({"mechanism": result, "reward": reward_result}, indent=1))
    lines = ["# Mission mechanism classes (generated by `tools/missions/classes.py`)", "",
             f"{len(ms)} missions -> {len(result)} classes. `Rep` = representative to run on the oracle; deferred = social/rival types the user deferred.", "",
             "| Class | Type | Key | Members (default/alt) | Rep | Rep2 | Deferred |", "|---|---|---|---:|---|---|---|"]
    for c in result:
        d = len(c["default_members"]); n = len(c["members"])
        lines.append(f"| {c['class']} | {c['type']} | `{c['key']}` | {n} ({d}/{n - d}) | {c['representative']} | {c['second_representative'] or ''} | {'yes' if c['deferred'] else ''} |")
    todo = [c for c in result if not c["deferred"]]
    lines += ["", f"In scope: {len(todo)} classes, {sum(len(c['members']) for c in todo)} missions. Deferred: {len(result) - len(todo)} classes, {sum(len(c['members']) for c in result if c['deferred'])} missions."]
    lines += ["", "## Reward-shape classes (3 reward groups: base / A-B 1 / A-B 2)", "", "| Class | Key | Members | Rep |", "|---|---|---:|---|"]
    for r in reward_result:
        lines.append(f"| {r['class']} | `{r['key']}` | {len(r['members'])} | {r['representative']} |")
    (ROOT / "docs/missions-classes.md").write_text("\n".join(lines) + "\n")
    print(f"{len(ms)} missions -> {len(result)} mechanism classes ({len(todo)} in scope) + {len(reward_result)} reward-shape classes")


main()
