#!/usr/bin/env python3
"""Generate docs/missions-status.md: the ONLY authoritative mission status table.

Statuses (computed, never typed by hand):
  MATCH (oracle)      valid, equal evidence (tools/missions/evidence/*.json, file hashes unchanged) names this mission sku
  MATCH by class Cxx  the mission's mechanism class has a valid equal oracle run (representative or any member) AND the
                      synthetic sweep passes for every row AND the static sweep has no errors
  STATIC              reviewed by code reading only (tools/missions/manual.json, needs a citation); NOT an oracle result
  DEFERRED            social/rival types deferred by the user
  TODO                everything else
Reward shapes (R01..) are tracked separately per reward group (0/1/2) from evidence `reward_group`.
Usage: python3 tools/missions/mark.py [--skip-sweep]
"""
import hashlib, json, subprocess, sys, tempfile
from pathlib import Path
from common import ROOT, OUT, load_missions

HERE = Path(__file__).resolve().parent
EVID = HERE / "evidence"


def sha(p: Path) -> str:
    return hashlib.sha256(p.read_bytes()).hexdigest() if p.exists() else ""


def valid_evidence() -> list[dict]:
    acc = HERE / "accepted.json"
    out = []
    for f in sorted(EVID.glob("*.json")) if EVID.exists() else []:
        ev = json.loads(f.read_text())
        ok = ev.get("equal") is True and ev.get("accepted_sha") == (sha(acc) if acc.exists() else None)
        ok = ok and all(sha(Path(p)) == h for p, h in ev.get("files", {}).items())
        ev["_valid"] = ok
        ev["_file"] = f.name
        out.append(ev)
    return out


def run(cmd, cwd):
    return subprocess.run(cmd, cwd=cwd, capture_output=True, text=True)


def main():
    skip = "--skip-sweep" in sys.argv
    classes = json.loads((OUT / "classes.json").read_text())
    static = run([sys.executable, str(HERE / "static_sweep.py")], HERE).returncode == 0
    sweep = False
    if not skip:
        tmp = Path(tempfile.mkdtemp()) / "sweep.json"
        r = run(["npx", "vitest", "run", "test/missions-sweep.test.ts", "--reporter=json", f"--outputFile={tmp}"], ROOT / "apps/client")
        try:
            j = json.loads(tmp.read_text())
            sweep = j["numFailedTests"] == 0 and j["numPassedTests"] > 900
        except Exception:
            sweep = False
    ev = valid_evidence()
    manual = json.loads((HERE / "manual.json").read_text()) if (HERE / "manual.json").exists() else {}
    cls_of = {s: c for c in classes["mechanism"] for s in c["members"]}
    ev_by_sku = {}
    ev_by_class = {}
    for e in ev:
        if not e["_valid"]:
            continue
        for s in e["skus"]:
            ev_by_sku.setdefault(s, []).append(e["_file"])
        ev_by_class.setdefault(e["class"], []).append(e["_file"])
    rows, counts = [], {}
    for m in load_missions():
        sku, c = m["sku"], cls_of[m["sku"]]
        st, note = "TODO", ""
        if c["deferred"]:
            st = "DEFERRED"
        elif sku in ev_by_sku:
            st, note = "MATCH (oracle)", ", ".join(ev_by_sku[sku])
        elif c["class"] in ev_by_class and static and sweep:
            st, note = f"MATCH by class {c['class']}", ", ".join(ev_by_class[c["class"]])
        elif sku in manual:
            st, note = "STATIC", f"{manual[sku]['note']} ({manual[sku]['citation']})"
        counts[st.split(" by")[0]] = counts.get(st.split(" by")[0], 0) + 1
        rows.append((m["_set"], sku, m.get("missionName", ""), m["type"], c["class"], st, note))
    lines = ["# Mission status (generated by `tools/missions/mark.py`; do not edit)", "",
             f"static sweep OK: {static}; synthetic sweep OK: {sweep if not skip else 'skipped'}; valid evidence files: {sum(1 for e in ev if e['_valid'])}/{len(ev)}", "",
             "Counts: " + ", ".join(f"{k} {v}" for k, v in sorted(counts.items())), "",
             "| Set | SKU | Mission | Type | Class | Status | Evidence / note |", "|---|---:|---|---|---|---|---|"]
    lines += [f"| {a} | {b} | {c} | {d} | {e} | {f} | {g} |" for a, b, c, d, e, f, g in rows]
    lines += ["", "## Reward-shape classes x reward group (oracle evidence)", "", "| Class | Key | g0 | g1 | g2 |", "|---|---|---|---|---|"]
    for r in classes["reward"]:
        cells = []
        for g in (0, 1, 2):
            hit = [e["_file"] for e in ev if e["_valid"] and e.get("reward_group", 0) == g and set(e["skus"]) & set(r["members"])]
            cells.append(hit[0] if hit else "TODO")
        lines.append(f"| {r['class']} | `{r['key']}` | {' | '.join(cells)} |")
    if ev and any(not e["_valid"] for e in ev):
        lines += ["", "INVALID evidence (hash mismatch, not equal, or accepted.json changed): " + ", ".join(e["_file"] for e in ev if not e["_valid"])]
    (ROOT / "docs/missions-status.md").write_text("\n".join(lines) + "\n")
    print("Counts:", counts)


main()
